code --install-extension ms-python.python
code --install-extension eamodio.gitlens
code --install-extension vscode-icons-team.vscode-icons
code --install-extension TabNine.tabnine-vscode
code --install-extension zhuangtongfa.material-theme
code --install-extension coenraads.bracket-pair-colorizer-2
code --install-extension gruntfuggly.todo-tree
code --install-extension ms-toolsai.jupyter
code --install-extension xabikos.javascriptsnippets
code --install-extension dsznajder.es7-react-js-snippets
code --install-extension esbenp.prettier-vscode
